import {
  SENSEBOARD_AI_CONTENT_MAX_X,
  SENSEBOARD_AI_CONTENT_MIN_X,
  SENSEBOARD_AI_ELEMENT_MAX_HEIGHT,
  SENSEBOARD_AI_ELEMENT_MAX_WIDTH,
  SENSEBOARD_CANVAS_HEIGHT,
  SENSEBOARD_CANVAS_PADDING,
  SENSEBOARD_CANVAS_WIDTH,
} from '../../../../shared/board-dimensions';
import { clampNumber, type GuardBounds } from './numeric';

export const MAX_TEXT_LENGTH = 4000;
export const MAX_MOVE_DELTA = SENSEBOARD_CANVAS_WIDTH;
export const MIN_VIEWPORT_ZOOM = 0.05;
export const MAX_VIEWPORT_ZOOM = 6;
export const DEFAULT_PROVIDER_TAG = 'unknown-provider';
export const DEFAULT_BURST_WINDOW_MS = 2500;
export const DEFAULT_BURST_THRESHOLD = 3;
export const MAX_BURST_HISTORY_ENTRIES = 128;
export const BURST_HISTORY_TTL_MULTIPLIER = 4;

export const CANVAS_ELEMENT_BOUNDS: GuardBounds = {
  minX: SENSEBOARD_CANVAS_PADDING,
  maxX: SENSEBOARD_CANVAS_WIDTH - SENSEBOARD_CANVAS_PADDING,
  minY: SENSEBOARD_CANVAS_PADDING,
  maxY: SENSEBOARD_CANVAS_HEIGHT - SENSEBOARD_CANVAS_PADDING,
  maxWidth: Math.max(1, SENSEBOARD_CANVAS_WIDTH - SENSEBOARD_CANVAS_PADDING * 2),
  maxHeight: Math.max(1, SENSEBOARD_CANVAS_HEIGHT - SENSEBOARD_CANVAS_PADDING * 2),
};

const AI_MIN_X = clampNumber(SENSEBOARD_AI_CONTENT_MIN_X, CANVAS_ELEMENT_BOUNDS.minX, CANVAS_ELEMENT_BOUNDS.maxX - 1);
const AI_MAX_X = clampNumber(SENSEBOARD_AI_CONTENT_MAX_X, AI_MIN_X + 1, CANVAS_ELEMENT_BOUNDS.maxX);

export const AI_ELEMENT_BOUNDS: GuardBounds = {
  minX: AI_MIN_X,
  maxX: AI_MAX_X,
  minY: CANVAS_ELEMENT_BOUNDS.minY,
  maxY: CANVAS_ELEMENT_BOUNDS.maxY,
  maxWidth: Math.max(1, Math.min(SENSEBOARD_AI_ELEMENT_MAX_WIDTH, AI_MAX_X - AI_MIN_X)),
  maxHeight: Math.max(1, Math.min(SENSEBOARD_AI_ELEMENT_MAX_HEIGHT, CANVAS_ELEMENT_BOUNDS.maxHeight)),
};
